### ISSUE TITLE
No carga

### ISSUE THREAD

**Issue by Gamerexde** [JosGCS/iAtomBot#1]
![image](https://user-images.githubusercontent.com/18222681/55033608-ee918800-4fe9-11e9-9440-67d0be76df17.png)

**Comment by JosGCS** [comment]
Hola @Gamerexde,

¡Gracias por tu reporte! Hemos solucionado el problema que nos has proporcionado, también recomendamos usar la plantilla para reportar bugs y así lograr una mejor eficacia por nuestra parte.

Saludos,
@JosGCS
